# Generated by Django 4.1.5 on 2023-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demi_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
